name: go-test application CI/CD workflow

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_ECR:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_public_key }}
        aws-secret-access-key: ${{ secrets.aws_private_key}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id:   ecr_login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push to ECR
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: |
          ${{ steps.ecr_login.outputs.registry }}:${{github.sha}}
          ${{ steps.ecr_login.outputs.registry }}:latest
