name: go-test application CI/CD workflow

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_public_key }}
        aws-secret-access-key: ${{ secrets.aws_private_key}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr_login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      id: build-image
      run: |
        docker build -t go-test:$GITHUB_SHA .
        docker tag go-test:$GITHUB_SHA go-test:latest
        
    - name: Push Docker image to Amazon ECR
      id: push-image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p4y8p3t2
        docker push go-test:$GITHUB_SHA
        docker push go-test:latest